services:
  # Servicio PostgreSQL
  db:
    image: postgres:17-alpine
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 2s
      timeout: 2s
      retries: 15
    restart: "no"

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgesparterpubli@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

  # API
  api:
    build:
      context: ./API
      dockerfile: Dockerfile.API
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  # DBT
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile.pyDBT
    container_name: dbt
    volumes:
      - ./dbt:/usr/app/dbt
      - ~/.dbt:/home/appuser/.dbt
    working_dir: /usr/app/dbt
    command: >
      bash -c "dbt deps && dbt build --target dev"
    depends_on:
      - db

  # Ingestion
  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile.pyIngestion
    image: ingestion:latest
  ingestion_311:
    build:
      context: ./ingestion
      dockerfile: Dockerfile.311
    image: ingestion_311:latest
    container_name: ingestion_311
    depends_on:
      - db
    networks:
      - dp1_network

  # Ingestion 911
  ingestion_911:
    build:
      context: ./ingestion
      dockerfile: Dockerfile.911
    image: ingestion_911:latest
    container_name: ingestion_911
    depends_on:
      - db
    networks:
      - dp1_network
      
  # Dashboard
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.pyDASH
    container_name: plotly_dashboard
    ports:
      - "8050:8050"
    depends_on:
      - db
    networks:
      - dp1_network

volumes:
  postgres-data:
  pgadmin_data:

networks:
  dp1_network:
    driver: bridge